version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli
  build:
    commands:
      - aws cloudformation package \
          --template-file template.yml \
          --s3-bucket lambda-artifacts-prod \
          --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
